version: '3.9'
services:
  api: 
    container_name: api_random
    restart: on-failure
    build: ./api
    ports:
      - 8080:8080
    expose: [8080]
  dw:
    container_name: db_dw
    restart: on-failure
    build: ./dw
    ports:
      - 3307:3306
    expose: [3307]