-- MySQL Script generated by MySQL Workbench
-- Sun Oct 15 16:19:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trabalho
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trabalho
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trabalho` ;
USE `trabalho` ;

-- -----------------------------------------------------
-- Table `trabalho`.`DIM_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`DIM_CLIENTE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `IDADE` INT NOT NULL,
  `GENERO` VARCHAR(20) NOT NULL,
  `NOME` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`DIM_PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`DIM_PRODUTO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  `COR` VARCHAR(100) NOT NULL,
  `TAMANHO` VARCHAR(5) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`DIM_ESTACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`DIM_ESTACAO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`DIM_LOCALIZACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`DIM_LOCALIZACAO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CIDADE` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`FATO_VENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`FATO_VENDA` (
  `DIM_CLIENTE_ID` INT NOT NULL,
  `DIM_PRODUTO_ID` INT NOT NULL,
  `DIM_ESTACAO_ID` INT NOT NULL,
  `DIM_LOCALIZACAO_ID` INT NOT NULL,
  `VALOR` FLOAT NOT NULL,
  PRIMARY KEY (`DIM_CLIENTE_ID`, `DIM_PRODUTO_ID`, `DIM_ESTACAO_ID`, `DIM_LOCALIZACAO_ID`),
  INDEX `fk_FATO_VENDA_DIM_PRODUTO1_idx` (`DIM_PRODUTO_ID` ASC) VISIBLE,
  INDEX `fk_FATO_VENDA_DIM_ESTACAO1_idx` (`DIM_ESTACAO_ID` ASC) VISIBLE,
  INDEX `fk_FATO_VENDA_DIM_LOCALIZACAO1_idx` (`DIM_LOCALIZACAO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_FATO_VENDA_DIM_CLIENTE`
    FOREIGN KEY (`DIM_CLIENTE_ID`)
    REFERENCES `trabalho`.`DIM_CLIENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FATO_VENDA_DIM_PRODUTO1`
    FOREIGN KEY (`DIM_PRODUTO_ID`)
    REFERENCES `trabalho`.`DIM_PRODUTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FATO_VENDA_DIM_ESTACAO1`
    FOREIGN KEY (`DIM_ESTACAO_ID`)
    REFERENCES `trabalho`.`DIM_ESTACAO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FATO_VENDA_DIM_LOCALIZACAO1`
    FOREIGN KEY (`DIM_LOCALIZACAO_ID`)
    REFERENCES `trabalho`.`DIM_LOCALIZACAO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
